spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: duongminhson1601@gmail.com
    password: zzlr poti vosg dcvt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    # secret nên là chuỗi base64 dài (>= 256 bit) và lưu ở secret manager trên production
    secret: "BASE64_ENCODED_SECRET_GOES_HERE"
    verification-token-ttl-minutes: 10